from typing import TypedDict, Optional, Literal, Any
from datetime import datetime


# --- Enums ---

RoutingSignal = Literal[
    "to_reconciliation",    # UC01 → UC02 (bank statement path)
    "to_ap",               # UC01 → UC05 (supplier invoice path)
    "to_ar",               # Supervisor → UC04 (accounts receivable path)
    "to_reporting",        # Supervisor → UC06 (reporting path)
    "duplicate_bill",       # UC05: AP Agent detected a duplicate invoice
    "nothing_to_collect",   # UC04: no overdue AR invoices found
    "no_report_data",      # UC06: no reporting data available
    "unrecognized",         # UC01 alt: unclassifiable document → N4
    "nothing_to_reconcile", # UC02 alt: no pending transactions
    "hitl_pending",         # UC02/UC04/UC05/UC06 → UC03
    "completed",            # cycle completed cleanly
]

HitlDecision = Literal[
    "approve",
    "modify",
    "block",
    "timeout",
]

EscalationLevel = Literal["N1", "N2", "N3", "N4"]

APDecision = Literal["auto_approved", "flagged", "hitl_required", "duplicate"]

ARActionTaken = Literal[
    "reminder_sent",          # N1: auto-reminder dispatched
    "second_reminder_sent",   # N2: second reminder + flagged for review
    "hitl_required",          # N3: human approval required
    "unrecognized_client",    # N4: disputed or unidentifiable client
]

DocumentType = Literal[
    "supplier_invoice",
    "bank_statement",
    "receipt",
    "other",
]


# --- Sub-types ---

class IngestedDocument(TypedDict):
    document_id: str          # UUID generated at ingestion
    document_type: DocumentType
    date: str                 # ISO 8601
    amount: float             # CAD
    currency: str             # "CAD" for MVP
    vendor_or_client: str
    document_number: str
    qbo_entry_id: str         # ID returned by QBO MCP after creation
    source_email_id: str      # Gmail message ID (source)


class ReconciliationGap(TypedDict):
    gap_id: str               # UUID
    document_id: str          # reference to IngestedDocument
    transaction_id: str       # QBO ID of unmatched transaction
    expected_amount: float    # expected amount (CAD)
    actual_amount: float      # actual amount found (CAD)
    delta: float              # actual - expected
    date_expected: str        # ISO 8601
    date_actual: str          # ISO 8601
    vendor_or_client: str
    escalation_level: EscalationLevel  # N1 if delta < 500, N3 if delta > 2000


class APAction(TypedDict):
    action_id: str                    # UUID generated by AP Agent
    document_id: str                  # FK → IngestedDocument.document_id
    vendor: str                       # vendor name (from invoice)
    amount: float                     # invoice amount (CAD)
    decision: APDecision              # outcome of AP processing
    escalation_level: EscalationLevel # N1–N4
    timestamp: str                    # ISO 8601 UTC
    notes: str                        # human-readable reason for decision


class ARAction(TypedDict):
    invoice_id: str                   # QBO invoice ID or generated UUID
    client: str                       # client name
    amount_cad: float                 # outstanding invoice amount (CAD)
    days_overdue: int                 # days past due date at processing time
    action_taken: ARActionTaken       # what the AR Agent did
    escalation_level: EscalationLevel # N1–N4
    timestamp: str                    # ISO 8601 UTC


class ARAgingBucket(TypedDict):
    bucket_label: str   # "0-30 days" | "31-60 days" | "61-90 days" | "90+ days"
    count: int          # number of invoices in this bucket
    total_cad: float    # total outstanding amount (CAD)


class ReportData(TypedDict):
    period: str                 # reporting period — "YYYY-MM"
    revenue: float              # total revenue (CAD)
    expenses: float             # total expenses (CAD)
    net_income: float           # revenue - expenses (CAD)
    cash_flow: float            # net cash flow (CAD); negative = net outflow
    ar_aging: list[ARAgingBucket]
    ap_summary: dict            # {"total_cad": float, "overdue_count": int}
    anomalies: list[str]        # human-readable descriptions of detected anomalies


# --- Main SharedState ---

class AccountingAgentsState(TypedDict):

    # ── Input document (UC01) ─────────────────────────────────────
    input_document: Optional[dict]
    # Raw incoming document injected before graph.invoke().
    # Written by: test harness (MVP) / Gmail MCP (Phase 2)
    # Read by: Ingestion Agent
    # Fields: raw_text, source_email_id, filename

    # ── Ingestion (UC01) ──────────────────────────────────────────
    documents_ingested: list[IngestedDocument]
    # Documents processed in this cycle.
    # Written by: Ingestion Agent
    # Read by: Reconciliation Agent, Supervisor

    # ── Routing (UC01, UC02) ──────────────────────────────────────
    routing_signal: Optional[RoutingSignal]
    # Routing signal emitted by the current agent.
    # Written by: Ingestion Agent, Reconciliation Agent
    # Read by: Supervisor (conditional routing)

    # ── Reconciliation (UC02) ─────────────────────────────────────
    reconciliation_gaps: list[ReconciliationGap]
    # Gaps detected during reconciliation.
    # Written by: Reconciliation Agent
    # Read by: Supervisor, HITL notifier

    # ── AP (UC05) ─────────────────────────────────────────────────
    ap_actions: list[APAction]
    # Accounts payable actions taken in this cycle.
    # Written by: AP Agent
    # Read by: Supervisor, HITL notifier

    # ── AR (UC04) ─────────────────────────────────────────────────
    ar_invoices: Optional[list[dict]]
    # Open QBO invoices for AR processing.
    # None  → AR Agent uses built-in mock fixture (AR_MODE=mock default)
    # []    → explicitly empty — no invoices to process
    # [...] → injected invoice list (tests or QBO MCP fetch result)
    # Written by: test harness (mock) / QBO MCP (Phase 4)
    # Read by: AR Agent
    # Fields per invoice: invoice_id, client, amount_cad, due_date, currency, disputed

    ar_actions: list[ARAction]
    # Accounts receivable actions taken in this cycle.
    # Written by: AR Agent
    # Read by: Supervisor, HITL notifier

    # ── Reporting (UC06) ──────────────────────────────────────────
    reporting_input: Optional[dict]
    # Raw QBO data for the Reporting Agent.
    # None  → Reporting Agent uses built-in mock fixture (REPORTING_MODE=mock)
    # {}    → explicitly empty — no data to report
    # {...} → injected data (tests or QBO MCP fetch result)
    # Written by: test harness (mock) / QBO MCP (Phase 4)
    # Read by: Reporting Agent
    # Keys: period, current {revenue, expenses, net_income, cash_flow,
    #                         ar_aging, ap_summary}, previous {revenue, expenses}

    report_data: Optional[ReportData]
    # Structured report output produced by the Reporting Agent.
    # Written by: Reporting Agent (N1/N2 only — not sent if N3/N4)
    # Read by: Supervisor, HITL notifier

    report_sent: bool
    # True if the formatted report was dispatched (N1/N2 paths).
    # Written by: Reporting Agent
    # Read by: Supervisor

    # ── HITL (UC03) ───────────────────────────────────────────────
    hitl_pending: bool
    # True if an interrupt() is awaiting human decision.
    # Written by: Reconciliation Agent (set True), Webhook (set False)
    # Read by: Supervisor

    hitl_decision: Optional[HitlDecision]
    # Decision received via webhook after mobile approval.
    # Written by: FastAPI Webhook
    # Read by: Supervisor (post-HITL routing)

    hitl_comment: Optional[str]
    # Optional accountant comment ("modify" decision only).
    # Written by: FastAPI Webhook
    # Read by: Reconciliation Agent (re-route with constraint)

    thread_id: str
    # LangGraph thread ID — required for post-interrupt() resumption.
    # Written by: Supervisor at initialization
    # Read by: FastAPI Webhook, SqliteSaver

    timeout_at: Optional[datetime]
    # HITL expiration timestamp (now + 4h).
    # Written by: Supervisor at interrupt()
    # Read by: Timeout handler

    # ── Errors & audit (all UCs) ──────────────────────────────────
    error_log: list[str]
    # Non-fatal errors accumulated during the cycle.
    # Written by: all agents
    # Read by: Supervisor


# --- Initial state ---

def initial_state(thread_id: str) -> AccountingAgentsState:
    """Return a clean initial state for a new cycle."""
    return AccountingAgentsState(
        input_document=None,
        documents_ingested=[],
        routing_signal=None,
        reconciliation_gaps=[],
        ap_actions=[],
        ar_invoices=None,
        ar_actions=[],
        reporting_input=None,
        report_data=None,
        report_sent=False,
        hitl_pending=False,
        hitl_decision=None,
        hitl_comment=None,
        thread_id=thread_id,
        timeout_at=None,
        error_log=[],
    )
