"""
Seed QBO sandbox with vendors and bills for Phase 2 integration testing.

Usage:
    PYTHONPATH=. .venv/bin/python scripts/seed_qbo_sandbox.py

Requires qbo_token.json at repo root (generated by generate_qbo_token.py).
Saves created QBO IDs to scripts/qbo_seed_ids.json.
"""

import json
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import requests
from dotenv import load_dotenv
from intuitlib.client import AuthClient

load_dotenv()

TOKEN_FILE = "qbo_token.json"
SEED_IDS_FILE = "scripts/qbo_seed_ids.json"
QBO_BASE_URL = "https://sandbox-quickbooks.api.intuit.com"
MINOR_VERSION = "65"

# Expense account IDs confirmed present in this sandbox company
ACCOUNT_UTILITIES = "27"        # Utilities — Hydro-Québec
ACCOUNT_TELEPHONE = "70"        # Telephone Expense — Bell / Vidéotron
ACCOUNT_OFFICE = "13"           # Office expenses — Fournisseur Général

VENDORS_TO_CREATE = [
    {"name": "Hydro-Québec",          "account_id": ACCOUNT_UTILITIES, "amount": 2450.00, "date": "2026-03-22"},
    {"name": "Bell Canada",            "account_id": ACCOUNT_TELEPHONE, "amount":  320.00, "date": "2026-03-15"},
    {"name": "Vidéotron",             "account_id": ACCOUNT_TELEPHONE, "amount":  185.00, "date": "2026-03-10"},
    {"name": "Fournisseur Général Inc.", "account_id": ACCOUNT_OFFICE,  "amount": 1200.00, "date": "2026-03-05"},
]


# ── Token management ─────────────────────────────────────────────

def load_token() -> dict:
    with open(TOKEN_FILE) as f:
        return json.load(f)


def save_token(token_data: dict) -> None:
    with open(TOKEN_FILE, "w") as f:
        json.dump(token_data, f, indent=2)


def get_access_token(token_data: dict) -> str:
    """Return a valid access token, refreshing if expired."""
    expiry = datetime.fromisoformat(token_data["token_expiry"])
    if datetime.now(timezone.utc) < expiry:
        return token_data["access_token"]

    print("🔄 Access token expired — refreshing...")
    auth_client = AuthClient(
        client_id=os.environ["QBO_CLIENT_ID"],
        client_secret=os.environ["QBO_CLIENT_SECRET"],
        redirect_uri="http://localhost:8080",
        environment=os.environ.get("QBO_ENVIRONMENT", "sandbox"),
        refresh_token=token_data["refresh_token"],
    )
    auth_client.refresh(refresh_token=token_data["refresh_token"])

    new_token = {
        "access_token": auth_client.access_token,
        "refresh_token": auth_client.refresh_token,
        "realm_id": token_data["realm_id"],
        "token_expiry": (
            datetime.now(timezone.utc) + timedelta(seconds=auth_client.expires_in)
        ).isoformat(),
    }
    save_token(new_token)
    print("✅ Token refreshed and saved")
    return auth_client.access_token


# ── QBO REST helpers ─────────────────────────────────────────────

def qbo_headers(access_token: str) -> dict:
    return {
        "Authorization": f"Bearer {access_token}",
        "Accept": "application/json",
        "Content-Type": "application/json",
    }


def qbo_post(endpoint: str, payload: dict, access_token: str, realm_id: str) -> dict:
    url = f"{QBO_BASE_URL}/v3/company/{realm_id}/{endpoint}?minorversion={MINOR_VERSION}"
    resp = requests.post(url, headers=qbo_headers(access_token), json=payload)
    if not resp.ok:
        raise RuntimeError(
            f"QBO POST /{endpoint} failed {resp.status_code}: {resp.text[:400]}"
        )
    return resp.json()


def qbo_query(query: str, access_token: str, realm_id: str) -> dict:
    url = f"{QBO_BASE_URL}/v3/company/{realm_id}/query"
    resp = requests.get(
        url,
        headers=qbo_headers(access_token),
        params={"query": query, "minorversion": MINOR_VERSION},
    )
    if not resp.ok:
        raise RuntimeError(f"QBO query failed {resp.status_code}: {resp.text[:400]}")
    return resp.json()


# ── Entity creation ──────────────────────────────────────────────

def find_vendor(name: str, access_token: str, realm_id: str) -> str | None:
    """Return existing vendor ID if found, else None."""
    safe_name = name.replace("'", "\\'")
    data = qbo_query(
        f"select * from Vendor where DisplayName='{safe_name}'",
        access_token, realm_id,
    )
    vendors = data.get("QueryResponse", {}).get("Vendor", [])
    return vendors[0]["Id"] if vendors else None


def create_vendor(name: str, access_token: str, realm_id: str) -> dict:
    existing_id = find_vendor(name, access_token, realm_id)
    if existing_id:
        print(f"  ↩  Vendor already exists: {name!r} (id={existing_id})")
        return {"id": existing_id, "name": name, "action": "existing"}

    payload = {"DisplayName": name}
    data = qbo_post("vendor", payload, access_token, realm_id)
    vendor_id = data["Vendor"]["Id"]
    print(f"  ✅ Vendor created: {name!r} (id={vendor_id})")
    return {"id": vendor_id, "name": name, "action": "created"}


def create_bill(
    vendor_id: str,
    vendor_name: str,
    amount: float,
    txn_date: str,
    account_id: str,
    access_token: str,
    realm_id: str,
) -> dict:
    due_date = (
        datetime.strptime(txn_date, "%Y-%m-%d") + timedelta(days=30)
    ).strftime("%Y-%m-%d")

    payload = {
        "VendorRef": {"value": vendor_id},
        "TxnDate": txn_date,
        "DueDate": due_date,
        "Line": [
            {
                "Amount": amount,
                "DetailType": "AccountBasedExpenseLineDetail",
                "AccountBasedExpenseLineDetail": {
                    "AccountRef": {"value": account_id},
                    "BillableStatus": "NotBillable",
                },
            }
        ],
    }
    data = qbo_post("bill", payload, access_token, realm_id)
    bill = data["Bill"]
    print(
        f"  ✅ Bill created: {vendor_name!r}  ${amount:,.2f} CAD"
        f"  TxnDate={txn_date}  due={due_date}  id={bill['Id']}"
    )
    return {
        "id": bill["Id"],
        "vendor_name": vendor_name,
        "vendor_id": vendor_id,
        "amount": amount,
        "txn_date": txn_date,
        "due_date": due_date,
        "account_id": account_id,
    }


# ── Main ─────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("QBO Sandbox Seeding — Phase 2 Integration Test Data")
    print("=" * 60)

    token_data = load_token()
    access_token = get_access_token(token_data)
    realm_id = token_data["realm_id"]

    print(f"\nRealm ID : {realm_id}")
    print(f"Base URL : {QBO_BASE_URL}\n")

    # ── Step 1: Create vendors ───────────────────────────────────
    print("STEP 1 — Vendors")
    print("-" * 40)
    vendor_results = []
    for spec in VENDORS_TO_CREATE:
        result = create_vendor(spec["name"], access_token, realm_id)
        vendor_results.append(result)

    vendor_map = {r["name"]: r["id"] for r in vendor_results}

    # ── Step 2: Create bills ─────────────────────────────────────
    print("\nSTEP 2 — Bills")
    print("-" * 40)
    bill_results = []
    for spec in VENDORS_TO_CREATE:
        vendor_id = vendor_map[spec["name"]]
        bill = create_bill(
            vendor_id=vendor_id,
            vendor_name=spec["name"],
            amount=spec["amount"],
            txn_date=spec["date"],
            account_id=spec["account_id"],
            access_token=access_token,
            realm_id=realm_id,
        )
        bill_results.append(bill)

    # ── Step 3: Save IDs ─────────────────────────────────────────
    seed_ids = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "realm_id": realm_id,
        "vendors": vendor_results,
        "bills": bill_results,
    }

    Path(SEED_IDS_FILE).parent.mkdir(parents=True, exist_ok=True)
    with open(SEED_IDS_FILE, "w") as f:
        json.dump(seed_ids, f, indent=2, ensure_ascii=False)

    # ── Summary ──────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(f"Vendors : {len(vendor_results)}")
    for v in vendor_results:
        print(f"  [{v['action']:8}] id={v['id']:>5}  {v['name']}")

    print(f"\nBills   : {len(bill_results)}")
    for b in bill_results:
        print(f"  id={b['id']:>5}  ${b['amount']:>8,.2f} CAD  {b['vendor_name']}")

    print(f"\nSeed IDs saved to: {SEED_IDS_FILE}")
    print("✅ qbo_token.json generated successfully")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"\n❌ Error: {exc}", file=sys.stderr)
        sys.exit(1)
